<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NeedsSystemTextJsonPackage>$([System.Text.RegularExpressions.Regex]::IsMatch('$(TargetFramework)', 'netstandard|net4'))</NeedsSystemTextJsonPackage>
  </PropertyGroup>
  <ItemGroup>
    <!-- Source Generator Dependencies -->
    <PackageVersion Include="Meziantou.Polyfill" Version="1.0.164" />
    <PackageVersion Condition="$(TargetFramework) == 'net462'"
                    Include="System.ValueTuple" Version="4.6.2"  />
    <PackageVersion Condition="$(NeedsSystemTextJsonPackage)"
                    Include="System.Text.Json" Version="10.0.11" /> <!-- JsonIgnoreAttribute -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.9.0" />
    <!-- Build Tools -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.4" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <!-- Testing -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="FluentAssertions" Version="8.10.0" />
    <!-- Benchmarking -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>
</Project>